# Generated by Django 2.1.3 on 2018-11-22 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0004_auto_20181121_1124'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academy.Session')),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('present', 'Present'), ('unexcused', 'Unexcused'), ('excused', 'Excused'), ('late', 'Late')], max_length=50)),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academy.Attendance')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='notes',
            field=models.TextField(default='', max_length=5000),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academy.Student'),
        ),
    ]
