# Generated by Django 2.1.3 on 2018-11-22 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0005_auto_20181122_0014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='session',
        ),
        migrations.RemoveField(
            model_name='attendancerecord',
            name='attendance',
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='session',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='academy.Session'),
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
