# Generated by Django 2.1.3 on 2018-11-22 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0006_auto_20181122_0017'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='session_nember',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('excused', 'Excused'), ('late', 'Late')], max_length=50),
        ),
    ]
