# Generated by Django 2.1.3 on 2018-11-23 19:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0008_auto_20181123_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='date_datetime',
            field=models.DateField(default=datetime.datetime(2018, 11, 23, 19, 33, 18, 1937, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
