# Generated by Django 2.1.3 on 2018-11-23 21:22

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0009_session_date_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='color1',
            field=colorfield.fields.ColorField(default='#FFF', max_length=18),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='class',
            name='color2',
            field=colorfield.fields.ColorField(default='#FFF', max_length=18),
            preserve_default=False,
        ),
    ]
