# Generated by Django 2.1.3 on 2018-11-23 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0010_auto_20181123_1622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='color1',
        ),
        migrations.RemoveField(
            model_name='class',
            name='color2',
        ),
    ]
