# Generated by Django 2.1.3 on 2018-11-23 21:28

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0011_auto_20181123_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='color1',
            field=colorfield.fields.ColorField(default='#3f51b5', max_length=18),
        ),
        migrations.AddField(
            model_name='class',
            name='color2',
            field=colorfield.fields.ColorField(default='#ffc107', max_length=18),
        ),
    ]
