# Generated by Django 2.1.3 on 2018-11-24 03:28

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0012_auto_20181123_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='color1',
            field=colorfield.fields.ColorField(default=0, max_length=18),
        ),
        migrations.AlterField(
            model_name='class',
            name='color2',
            field=colorfield.fields.ColorField(default=17, max_length=18),
        ),
        migrations.AlterField(
            model_name='class',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accountviews.Teacher'),
        ),
        migrations.AlterField(
            model_name='course',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accountviews.Admin'),
        ),
        migrations.AlterField(
            model_name='school',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accountviews.Admin'),
        ),
    ]
